services:
  qupath-env:
    image: gnasello/qupath-env:2024-08-23
    container_name: qupath
    security_opt:
      - seccomp:unconfined # for terminal to work
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    #volumes:
      #- /home/path/:/config/researcher_home
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
      - 3001:3001
    #devices:
      #- /dev/dri:/dev/dri #optional
    #shm_size: "1gb" #optional